#define integer_ 1
#define float_ 2
#define string_ 3
#define char_ 4
#define bool_ 5
#define open_bracket_ 6
#define close_bracket_ 7
#define open_curly_braces_ 8
#define close_curly_braces_ 9
#define semicolumn_ 10
#define dt_int_ 11
#define dt_float_ 12
#define dt_char_ 13
#define dt_bool_ 14
#define dt_string_ 14
#define const_ 15
#define assign_ 16
#define minus_ 17
#define plus_ 18
#define divide_ 19
#define multiply_ 20
#define modulus_ 21
#define logical_not_ 22
#define logical_and_ 23
#define logical_or_ 24
#define gt_ 25
#define lt_ 26
#define gte_ 27
#define lte_ 28
#define not_equal_ 29
#define equals_ 30
#define if_ 31
#define else_ 32
#define while_ 33
#define repeat_ 34
#define until_ 35
#define for_ 36
#define column_ 37
#define break_ 38
#define continue_ 39
#define switch_ 40
#define case_ 41
#define default_ 42
