#define _integer 1
#define _float 2
#define _string 3
#define _char 4
#define _bool 5
#define _open_bracket 6
#define _close_bracket 7
#define _open_curly_braces 8
#define _close_curly_braces 9
#define _semicolumn 10
#define _dt_int 11
#define _dt_float 12
#define _dt_char 13
#define _dt_bool 14
#define _dt_string 14
#define _const 15
#define _assign 16
#define _minus 17
#define _plus 18
#define _divide 19
#define _multiply 20
#define _modulus 21
#define _logical_not 22
#define _logical_and 23
#define _logical_or 24
#define _gt 25
#define _lt 26
#define _gte 27
#define _lte 28
#define _not_equal 29
#define _equals 30
#define _if 31
#define _else 32
#define _while 33
#define _repeat 34
#define _until 35
#define _for 36
#define _column 37
#define _break 38
#define _continue 39
#define _switch 40
#define _case 41
#define _default 42
